import { defineType, defineField } from "sanity";

export const pagesContent = defineType({
  name: "pagesContent",
  title: "Pages Content",
  type: "document",
  fieldsets: [
    { name: "places", title: "Places Page", options: { collapsible: true, collapsed: true } },
    { name: "experiencesListing", title: "Experiences Listing Page", options: { collapsible: true, collapsed: true } },
    { name: "guidesListing", title: "Guides Listing Page", options: { collapsible: true, collapsed: true } },
    { name: "authors", title: "Authors Page", options: { collapsible: true, collapsed: true } },
    { name: "saved", title: "Saved Page", options: { collapsible: true, collapsed: true } },
    { name: "dashboard", title: "Dashboard Page", options: { collapsible: true, collapsed: true } },
    { name: "account", title: "Account Page", options: { collapsible: true, collapsed: true } },
    { name: "signIn", title: "Sign In Page", options: { collapsible: true, collapsed: true } },
    { name: "notFound", title: "404 Page", options: { collapsible: true, collapsed: true } },
    { name: "itinerary", title: "Itinerary Page", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    // ── Places ──────────────────────────────────
    defineField({
      name: "placesHeading",
      title: "Heading",
      type: "string",
      fieldset: "places",
      initialValue: "Temples, backstreets, and the restaurants your guidebook missed.",
    }),
    defineField({
      name: "placesSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "places",
      initialValue: "Filter by what matters to you, or pan the map to explore.",
    }),
    defineField({
      name: "placesErrorMessage",
      title: "Error Message",
      type: "string",
      fieldset: "places",
      initialValue: "Something went wrong loading places",
    }),
    defineField({
      name: "placesRetryText",
      title: "Retry Button Text",
      type: "string",
      fieldset: "places",
      initialValue: "Try again",
    }),
    defineField({
      name: "placesEndMessage",
      title: "End of List Message",
      type: "string",
      fieldset: "places",
      description: "Use {count} as placeholder for the total number of places.",
      initialValue: "That's all {count}. For now.",
    }),

    // ── Experiences Listing ──────────────────────
    defineField({
      name: "experiencesHeading",
      title: "Hero Heading",
      type: "string",
      fieldset: "experiencesListing",
      initialValue: "Workshops, cruises, and the kind of moments you'll talk about for years.",
    }),
    defineField({
      name: "experiencesDescription",
      title: "Hero Description",
      type: "string",
      fieldset: "experiencesListing",
      initialValue: "Hands-on moments you won't find in any guidebook.",
    }),
    defineField({
      name: "experiencesEmptyHeading",
      title: "Empty State Heading",
      type: "string",
      fieldset: "experiencesListing",
      initialValue: "Experiences are in the works",
    }),
    defineField({
      name: "experiencesEmptyDescription",
      title: "Empty State Description",
      type: "string",
      fieldset: "experiencesListing",
      initialValue: "We're putting these together now. Browse places while you wait.",
    }),
    defineField({
      name: "experiencesFilteredEmptyHeading",
      title: "Filtered Empty State Heading",
      type: "string",
      fieldset: "experiencesListing",
      initialValue: "No experiences of this type yet",
    }),
    defineField({
      name: "experiencesFilteredEmptyDescription",
      title: "Filtered Empty State Description",
      type: "string",
      fieldset: "experiencesListing",
      initialValue: "Try another filter, or see everything.",
    }),

    // ── Guides Listing ──────────────────────────
    defineField({
      name: "guidesHeading",
      title: "Hero Heading",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "What the locals know, written down for the first time.",
    }),
    defineField({
      name: "guidesDescription",
      title: "Hero Description",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "Organized by region, season, and the kind of trip you're after.",
    }),
    defineField({
      name: "guidesEmptyHeading",
      title: "Empty State Heading",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "Guides are in the works",
    }),
    defineField({
      name: "guidesEmptyDescription",
      title: "Empty State Description",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "We're writing them now. Explore places in the meantime.",
    }),
    defineField({
      name: "guidesFilteredEmptyHeading",
      title: "Filtered Empty State Heading",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "No guides in this category yet",
    }),
    defineField({
      name: "guidesFilteredEmptyDescription",
      title: "Filtered Empty State Description",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "Try another filter, or browse them all.",
    }),

    // ── Authors ─────────────────────────────────
    defineField({
      name: "authorsEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "authors",
      initialValue: "Our Authors",
    }),
    defineField({
      name: "authorsHeading",
      title: "Heading",
      type: "string",
      fieldset: "authors",
      initialValue: "Local Guide Authors",
    }),
    defineField({
      name: "authorsSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "authors",
      initialValue: "Meet the local experts behind our Japan travel guides",
    }),
    defineField({
      name: "authorsEmptyState",
      title: "Empty State Text",
      type: "string",
      fieldset: "authors",
      initialValue: "No authors yet. Check back soon.",
    }),

    // ── Saved ───────────────────────────────────
    defineField({
      name: "savedEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "saved",
      initialValue: "Saved",
    }),
    defineField({
      name: "savedTitle",
      title: "Title",
      type: "string",
      fieldset: "saved",
      initialValue: "Saved Places",
    }),
    defineField({
      name: "savedSubtitleWithCount",
      title: "Subtitle (with count)",
      type: "string",
      fieldset: "saved",
      description: "Use {count} as placeholder. Shown when saved places exist.",
      initialValue: "{count} places on your list.",
    }),
    defineField({
      name: "savedSubtitleEmpty",
      title: "Subtitle (empty)",
      type: "string",
      fieldset: "saved",
      initialValue: "Bookmark the places that catch your eye.",
    }),
    defineField({
      name: "savedBackgroundImage",
      title: "Header Background Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "saved",
    }),

    // ── Dashboard ───────────────────────────────
    defineField({
      name: "dashboardEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Home base",
    }),
    defineField({
      name: "dashboardSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Your trips, saved places, and plans in progress.",
    }),
    defineField({
      name: "dashboardActivityEyebrow",
      title: "Activity Section Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Activity",
    }),
    defineField({
      name: "dashboardActivityHeading",
      title: "Activity Section Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "At a Glance",
    }),
    defineField({
      name: "dashboardTripsEyebrow",
      title: "Trips Section Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Recent",
    }),
    defineField({
      name: "dashboardTripsHeading",
      title: "Trips Section Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Your Trips",
    }),
    defineField({
      name: "dashboardEmptyHeading",
      title: "Empty State Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "No trips yet",
    }),
    defineField({
      name: "dashboardEmptyDescription",
      title: "Empty State Description",
      type: "text",
      rows: 2,
      fieldset: "dashboard",
      initialValue: "Head to the trip builder to plan your first adventure. It'll appear here once it's ready.",
    }),
    defineField({
      name: "dashboardPlanButton",
      title: "Plan Button Text",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Start planning",
    }),
    defineField({
      name: "dashboardAccountEyebrow",
      title: "Account Section Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Account",
    }),
    defineField({
      name: "dashboardAccountHeading",
      title: "Account Section Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Profile & Sync",
    }),
    defineField({
      name: "dashboardDeleteToastTitle",
      title: "Delete Toast Title",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Itinerary deleted",
    }),
    defineField({
      name: "dashboardUndoButton",
      title: "Undo Button Text",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Undo",
    }),

    // ── Account ─────────────────────────────────
    defineField({
      name: "accountEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "account",
      initialValue: "Settings",
    }),
    defineField({
      name: "accountTitle",
      title: "Title",
      type: "string",
      fieldset: "account",
      initialValue: "Account",
    }),
    defineField({
      name: "accountSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "account",
      initialValue: "Profile, sync, and preferences.",
    }),
    defineField({
      name: "accountProfileHeading",
      title: "Profile Heading",
      type: "string",
      fieldset: "account",
      initialValue: "Profile",
    }),
    defineField({
      name: "accountSignOutText",
      title: "Sign Out Button Text",
      type: "string",
      fieldset: "account",
      initialValue: "Sign out",
    }),
    defineField({
      name: "accountDisplayNameLabel",
      title: "Display Name Label",
      type: "string",
      fieldset: "account",
      initialValue: "Display name",
    }),
    defineField({
      name: "accountClearDataText",
      title: "Clear Data Button Text",
      type: "string",
      fieldset: "account",
      initialValue: "Clear local data",
    }),
    defineField({
      name: "accountEmailLabel",
      title: "Email Label",
      type: "string",
      fieldset: "account",
      initialValue: "Email for magic link",
    }),
    defineField({
      name: "accountEmailPlaceholder",
      title: "Email Placeholder",
      type: "string",
      fieldset: "account",
      initialValue: "name@example.com",
    }),
    defineField({
      name: "accountSendLinkText",
      title: "Send Link Button Text",
      type: "string",
      fieldset: "account",
      initialValue: "Send sign-in link",
    }),

    // ── Sign In ─────────────────────────────────
    defineField({
      name: "signInHeading",
      title: "Left Panel Heading",
      type: "string",
      fieldset: "signIn",
      initialValue: "Welcome back",
    }),
    defineField({
      name: "signInDescription",
      title: "Left Panel Description",
      type: "string",
      fieldset: "signIn",
      initialValue: "Sign in to pick up where you left off.",
    }),
    defineField({
      name: "signInBackgroundImage",
      title: "Background Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "signIn",
    }),
    defineField({
      name: "signInFormHeading",
      title: "Form Heading",
      type: "string",
      fieldset: "signIn",
      initialValue: "Sign in with email",
    }),
    defineField({
      name: "signInFormDescription",
      title: "Form Description",
      type: "string",
      fieldset: "signIn",
      initialValue: "We'll send a magic link to your inbox.",
    }),
    defineField({
      name: "signInSubmitText",
      title: "Submit Button Text",
      type: "string",
      fieldset: "signIn",
      initialValue: "Send Sign-in Link",
    }),
    defineField({
      name: "signInNoAccountText",
      title: "No Account Info Text",
      type: "string",
      fieldset: "signIn",
      initialValue: "No account? One is created automatically.",
    }),
    defineField({
      name: "signInGuestText",
      title: "Guest Link Text",
      type: "string",
      fieldset: "signIn",
      initialValue: "Continue as guest",
    }),

    // ── 404 Page ───────────────────────────────
    defineField({
      name: "notFoundEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "notFound",
      initialValue: "Page not found",
    }),
    defineField({
      name: "notFoundHeading",
      title: "Heading",
      type: "string",
      fieldset: "notFound",
      initialValue: "Lost in Translation",
    }),
    defineField({
      name: "notFoundDescription",
      title: "Description",
      type: "string",
      fieldset: "notFound",
      initialValue: "This path leads nowhere — but Japan still has thousands waiting for you.",
    }),
    defineField({
      name: "notFoundPrimaryCtaText",
      title: "Primary CTA Text",
      type: "string",
      fieldset: "notFound",
      initialValue: "Take Me Home",
    }),
    defineField({
      name: "notFoundSecondaryCtaText",
      title: "Secondary CTA Text",
      type: "string",
      fieldset: "notFound",
      initialValue: "Explore Places",
    }),
    defineField({
      name: "notFoundBackgroundImage",
      title: "Background Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "notFound",
    }),

    // ── Itinerary ───────────────────────────────
    defineField({
      name: "itineraryLoadingText",
      title: "Loading Text",
      type: "string",
      fieldset: "itinerary",
      initialValue: "Loading...",
    }),
    defineField({
      name: "itineraryEmptyState",
      title: "Empty State Text",
      type: "string",
      fieldset: "itinerary",
      initialValue: "No itineraries yet. Build a trip and it'll show up here.",
    }),
    defineField({
      name: "itineraryBuilderLink",
      title: "Builder Link Text",
      type: "string",
      fieldset: "itinerary",
      initialValue: "Go to Trip Builder",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Pages Content" };
    },
  },
});
