import { defineType, defineField } from "sanity";

export const pagesContent = defineType({
  name: "pagesContent",
  title: "Pages Content",
  type: "document",
  fieldsets: [
    { name: "explore", title: "Explore Page", options: { collapsible: true, collapsed: true } },
    { name: "guidesListing", title: "Guides Listing Page", options: { collapsible: true, collapsed: true } },
    { name: "authors", title: "Authors Page", options: { collapsible: true, collapsed: true } },
    { name: "favorites", title: "Favorites Page", options: { collapsible: true, collapsed: true } },
    { name: "dashboard", title: "Dashboard Page", options: { collapsible: true, collapsed: true } },
    { name: "account", title: "Account Page", options: { collapsible: true, collapsed: true } },
    { name: "itinerary", title: "Itinerary Page", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    // ── Explore ─────────────────────────────────
    defineField({
      name: "exploreHeading",
      title: "Heading",
      type: "string",
      fieldset: "explore",
      initialValue: "Every temple, backstreet, and the restaurants your guidebook missed.",
    }),
    defineField({
      name: "exploreSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "explore",
      initialValue: "Filter by what matters. Tap any place to learn more.",
    }),
    defineField({
      name: "exploreErrorMessage",
      title: "Error Message",
      type: "string",
      fieldset: "explore",
      initialValue: "Unable to load destinations",
    }),
    defineField({
      name: "exploreRetryText",
      title: "Retry Button Text",
      type: "string",
      fieldset: "explore",
      initialValue: "Try again",
    }),
    defineField({
      name: "exploreEndMessage",
      title: "End of List Message",
      type: "string",
      fieldset: "explore",
      description: "Use {count} as placeholder for the total number of places.",
      initialValue: "All {count} places. More coming soon.",
    }),

    // ── Guides Listing ──────────────────────────
    defineField({
      name: "guidesEmptyHeading",
      title: "Empty State Heading",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "Guides are on the way",
    }),
    defineField({
      name: "guidesEmptyDescription",
      title: "Empty State Description",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "We're writing curated travel guides. Check back soon.",
    }),
    defineField({
      name: "guidesFilteredEmptyHeading",
      title: "Filtered Empty State Heading",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "Nothing here yet",
    }),
    defineField({
      name: "guidesFilteredEmptyDescription",
      title: "Filtered Empty State Description",
      type: "string",
      fieldset: "guidesListing",
      initialValue: "Try selecting a different category above.",
    }),

    // ── Authors ─────────────────────────────────
    defineField({
      name: "authorsEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "authors",
      initialValue: "Our Authors",
    }),
    defineField({
      name: "authorsHeading",
      title: "Heading",
      type: "string",
      fieldset: "authors",
      initialValue: "Local Guide Authors",
    }),
    defineField({
      name: "authorsSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "authors",
      initialValue: "Meet the local experts behind our Japan travel guides",
    }),
    defineField({
      name: "authorsEmptyState",
      title: "Empty State Text",
      type: "string",
      fieldset: "authors",
      initialValue: "No authors yet. Check back soon.",
    }),

    // ── Favorites ───────────────────────────────
    defineField({
      name: "favoritesEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "favorites",
      initialValue: "Saved",
    }),
    defineField({
      name: "favoritesTitle",
      title: "Title",
      type: "string",
      fieldset: "favorites",
      initialValue: "Favorites",
    }),
    defineField({
      name: "favoritesSubtitleWithCount",
      title: "Subtitle (with count)",
      type: "string",
      fieldset: "favorites",
      description: "Use {count} as placeholder. Shown when favorites exist.",
      initialValue: "{count} places on your list.",
    }),
    defineField({
      name: "favoritesSubtitleEmpty",
      title: "Subtitle (empty)",
      type: "string",
      fieldset: "favorites",
      initialValue: "Bookmark the places that catch your eye.",
    }),
    defineField({
      name: "favoritesBackgroundImage",
      title: "Header Background Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "favorites",
    }),

    // ── Dashboard ───────────────────────────────
    defineField({
      name: "dashboardEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Home base",
    }),
    defineField({
      name: "dashboardSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Your trips, saved places, and plans in progress.",
    }),
    defineField({
      name: "dashboardActivityEyebrow",
      title: "Activity Section Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Activity",
    }),
    defineField({
      name: "dashboardActivityHeading",
      title: "Activity Section Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "At a Glance",
    }),
    defineField({
      name: "dashboardTripsEyebrow",
      title: "Trips Section Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Recent",
    }),
    defineField({
      name: "dashboardTripsHeading",
      title: "Trips Section Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Your Trips",
    }),
    defineField({
      name: "dashboardEmptyHeading",
      title: "Empty State Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "No trips yet",
    }),
    defineField({
      name: "dashboardEmptyDescription",
      title: "Empty State Description",
      type: "text",
      rows: 2,
      fieldset: "dashboard",
      initialValue: "Head to the trip builder to plan your first adventure. It'll appear here once it's ready.",
    }),
    defineField({
      name: "dashboardPlanButton",
      title: "Plan Button Text",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Start planning",
    }),
    defineField({
      name: "dashboardAccountEyebrow",
      title: "Account Section Eyebrow",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Account",
    }),
    defineField({
      name: "dashboardAccountHeading",
      title: "Account Section Heading",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Profile & Sync",
    }),
    defineField({
      name: "dashboardDeleteToastTitle",
      title: "Delete Toast Title",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Itinerary deleted",
    }),
    defineField({
      name: "dashboardUndoButton",
      title: "Undo Button Text",
      type: "string",
      fieldset: "dashboard",
      initialValue: "Undo",
    }),

    // ── Account ─────────────────────────────────
    defineField({
      name: "accountEyebrow",
      title: "Eyebrow",
      type: "string",
      fieldset: "account",
      initialValue: "Settings",
    }),
    defineField({
      name: "accountTitle",
      title: "Title",
      type: "string",
      fieldset: "account",
      initialValue: "Account",
    }),
    defineField({
      name: "accountSubtitle",
      title: "Subtitle",
      type: "string",
      fieldset: "account",
      initialValue: "Profile, sync, and preferences.",
    }),
    defineField({
      name: "accountProfileHeading",
      title: "Profile Heading",
      type: "string",
      fieldset: "account",
      initialValue: "Profile",
    }),
    defineField({
      name: "accountSignOutText",
      title: "Sign Out Button Text",
      type: "string",
      fieldset: "account",
      initialValue: "Sign out",
    }),
    defineField({
      name: "accountDisplayNameLabel",
      title: "Display Name Label",
      type: "string",
      fieldset: "account",
      initialValue: "Display name",
    }),
    defineField({
      name: "accountClearDataText",
      title: "Clear Data Button Text",
      type: "string",
      fieldset: "account",
      initialValue: "Clear local data",
    }),
    defineField({
      name: "accountEmailLabel",
      title: "Email Label",
      type: "string",
      fieldset: "account",
      initialValue: "Email for magic link",
    }),
    defineField({
      name: "accountEmailPlaceholder",
      title: "Email Placeholder",
      type: "string",
      fieldset: "account",
      initialValue: "name@example.com",
    }),
    defineField({
      name: "accountSendLinkText",
      title: "Send Link Button Text",
      type: "string",
      fieldset: "account",
      initialValue: "Send sign-in link",
    }),

    // ── Itinerary ───────────────────────────────
    defineField({
      name: "itineraryLoadingText",
      title: "Loading Text",
      type: "string",
      fieldset: "itinerary",
      initialValue: "Loading...",
    }),
    defineField({
      name: "itineraryEmptyState",
      title: "Empty State Text",
      type: "string",
      fieldset: "itinerary",
      initialValue: "No itineraries yet. Build a trip and it'll show up here.",
    }),
    defineField({
      name: "itineraryBuilderLink",
      title: "Builder Link Text",
      type: "string",
      fieldset: "itinerary",
      initialValue: "Go to Trip Builder",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Pages Content" };
    },
  },
});
